# Generated by Django 3.1 on 2020-08-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bestdeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('prev_price', models.IntegerField(blank=True, null=True)),
                ('item_link', models.CharField(blank=True, max_length=255, null=True)),
                ('image_src', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('reviews', models.IntegerField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('per_discount', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bestdeal',
            },
        ),
    ]
