# Generated by Django 3.1 on 2020-08-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='total',
            field=models.IntegerField(default=1000),
        ),
    ]
