# Generated by Django 3.1 on 2020-08-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_usercart_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='total',
            field=models.BigIntegerField(default=1000),
        ),
    ]
